### ISSUE TITLE
Error: Service Unavailable

### ISSUE THREAD

**Issue by HeadTriXz** [MrJacz/hastebin-gen#33]
Hey,
I'm always getting the error: "Error: Service Unavailable".

**Comment by MrJacz** [comment]
Hey, @HeadTriXz that would be due to hastebin being generally always down.
you can pass your own hastebin server like this

```javascript
const haste = require("hastebin-gen");

const url = await haste("stuff here", { url: "https://paste.mod.gg" });
```
for example.
