### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by SpeedyCraftah** [MrJacz/hastebin-gen#46]
Doesn't work when trying to generate, no errors or anything

**Comment by MrJacz** [comment]
Can you please elaborate on the issue?

**Comment by pedroricardo** [comment]
I had a problem too 

`
Error: Service Unavailable

    at module.exports (/root/bot/node_modules/hastebin-gen/src/index.js:17:24)
    at process._tickCallback (internal/process/next_tick.js:68:7)
`

**Comment by Androz2091** [comment]
Try with this url: https://hasteb.in

So
```js
hastebin("test", { url: "https://hasteb.in" });
```

**Comment by MrJacz** [comment]
this is a problem with the hastebin.com site being t e r r i b l e and not the lib. i would recommend using any other hastebin clone :)
